# Generated by Django 5.2 on 2025-06-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sell_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bright',
        ),
    ]
