# Generated by Django 5.2 on 2025-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_staff_bright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='balance',
            field=models.FloatField(),
        ),
    ]
