# Generated by Django 5.2 on 2025-06-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_staff_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_payment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payment_set', to='home.staff'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_work_set', to='home.staff'),
        ),
    ]
