# Generated by Django 5.2 on 2025-07-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_staff_payment_staff_alter_staff_work_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
